#!/bin/sh
alias byeOrphans='sudo pacman -Rns $(pacman -Qtdq)'
alias cya="rm -rf"
alias dps="docker ps --format 'table {{.ID}}\t{{.Image}}\t{{.Names}}\t{{.Size}}\t{{.Status}}'"
alias gco='git checkout'
alias gss='git status'
alias gwa='git worktree add .wt/'
alias gwr='git worktree remove .wt/'
alias glo='git log --oneline --decorate --graph'
alias l="ls -alh --color=auto"
alias p="sudo pacman"
alias sudo='sudo '
alias e='$EDITOR'
alias vvd='cd "${DOTS}"'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias o='sesh connect $(sesh list | fzf)'

md(){
    mkdir -p $@ && cd $@
}
