#! /bin/sh

bspc monitor -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
